-- ============================================================
-- BARKASIN - Database Schema Migration
-- ============================================================
-- Jalankan script ini di SQL Editor Supabase:
-- https://supabase.com/dashboard/project/_/sql/new
-- ============================================================

-- ============================================================
-- 1. TABEL PROFILES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('seller', 'buyer', 'admin')),
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- RLS: User can read any profile (for seller name display)
CREATE POLICY "profiles_read_all" ON public.profiles
  FOR SELECT USING (true);

-- RLS: User can insert only own profile
CREATE POLICY "profiles_insert_own" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- RLS: User can update only own profile
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- ============================================================
-- 2. TRIGGER: Auto-create profile on signup
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'User'),
    COALESCE(NEW.raw_user_meta_data->>'role', 'buyer')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- 3. TABEL CATEGORIES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- RLS: Everyone can read categories
CREATE POLICY "categories_read_all" ON public.categories
  FOR SELECT USING (true);

-- ============================================================
-- 4. TABEL PRODUCTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  price BIGINT NOT NULL CHECK (price >= 0),
  description TEXT DEFAULT '',
  condition TEXT NOT NULL CHECK (condition IN ('Baru', 'Bekas')),
  location TEXT DEFAULT '',
  contact_phone TEXT DEFAULT '',
  contact_email TEXT DEFAULT '',
  is_admin_post BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- RLS: Everyone can read products
CREATE POLICY "products_read_all" ON public.products
  FOR SELECT USING (true);

-- RLS: Seller can insert own products
CREATE POLICY "products_insert_own" ON public.products
  FOR INSERT WITH CHECK (
    auth.uid() = seller_id
    OR
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- RLS: Seller can update own products (admin can update their own posts)
CREATE POLICY "products_update_own" ON public.products
  FOR UPDATE USING (
    auth.uid() = seller_id
    OR
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  )
  WITH CHECK (
    auth.uid() = seller_id
    OR
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- RLS: Seller can delete own products
CREATE POLICY "products_delete_own" ON public.products
  FOR DELETE USING (
    auth.uid() = seller_id
    OR
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- ============================================================
-- 5. TABEL PRODUCT IMAGES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  is_primary BOOLEAN DEFAULT false,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;

-- RLS: Everyone can read product images
CREATE POLICY "product_images_read_all" ON public.product_images
  FOR SELECT USING (true);

-- RLS: Seller can insert images for own products
CREATE POLICY "product_images_insert_own" ON public.product_images
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.products p
      WHERE p.id = product_id
        AND (
          p.seller_id = auth.uid()
          OR EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
          )
        )
    )
  );

-- RLS: Seller can delete images of own products
CREATE POLICY "product_images_delete_own" ON public.product_images
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM public.products p
      WHERE p.id = product_id
        AND (
          p.seller_id = auth.uid()
          OR EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
          )
        )
    )
  );

-- ============================================================
-- 6. SEED DATA: Categories
-- ============================================================
INSERT INTO public.categories (name, slug) VALUES
  ('Elektronik', 'elektronik'),
  ('Fashion', 'fashion'),
  ('Hobi & Olahraga', 'hobi-olahraga'),
  ('Rumah Tangga', 'rumah-tangga'),
  ('Otomotif', 'otomotif'),
  ('Properti', 'properti'),
  ('Buku & Alat Tulis', 'buku-alat-tulis'),
  ('Mainan & Bayi', 'mainan-bayi'),
  ('Kesehatan & Kecantikan', 'kesehatan-kecantikan'),
  ('Lainnya', 'lainnya')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- 7. INDEXES untuk performa
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_products_seller_id ON public.products(seller_id);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_created_at ON public.products(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_price ON public.products(price);
CREATE INDEX IF NOT EXISTS idx_products_condition ON public.products(condition);
CREATE INDEX IF NOT EXISTS idx_products_location ON public.products(location);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON public.product_images(product_id);

-- ============================================================
-- 8. STORAGE: Product images bucket
-- ============================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'product-images',
  'product-images',
  true,
  2097152,
  ARRAY['image/jpeg', 'image/png']
)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS: Anyone can view product images (public bucket)
CREATE POLICY "storage_read_product_images" ON storage.objects
  FOR SELECT USING (bucket_id = 'product-images');

-- Storage RLS: Authenticated users can upload to product-images
CREATE POLICY "storage_insert_product_images" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'product-images'
    AND auth.role() = 'authenticated'
  );

-- Storage RLS: Users can delete their own uploaded images
CREATE POLICY "storage_delete_product_images" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'product-images'
    AND auth.role() = 'authenticated'
  );
